import { Item } from "@/types/item";
import { Heading } from "@chakra-ui/react";
import axios from "axios";
import Head from "next/head";
import Link from "next/link";
import { useEffect, useState } from "react";

const NEXT_PUBLIC_API_URL = process.env.NEXT_PUBLIC_API_URL || "";

export default function Home() {
  const [items, setItems] = useState<Item[]>([]);

  useEffect(() => {
    async function fetchData() {
      try {
        const response = await axios.get(`${NEXT_PUBLIC_API_URL}/v1/items`, {
          headers: {
            "Content-Type": "application/json",
          },
        });
        setItems(response.data.items);
      } catch (error) {
        console.error("Error fetching items:", error);
      }
    }

    fetchData();
  }, []);
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Heading>Hey</Heading>

      <Link href="/create">Create New Item</Link>
      <ul>
        {items.map((item) => (
          <li key={item.id}>
            {item.uid} - {item.messageJson} ({item.sentDate})
            <Link href={`/update/${item.id}`}>Edit</Link>
          </li>
        ))}
      </ul>
    </>
  );
}
